# Generated by Django 5.1.7 on 2025-03-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0002_course_organization_remove_choice_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('cadet', 'Cadet'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='cadet', max_length=10),
        ),
    ]
